/*
 * This file is generated by jOOQ.
 */
package com.github.senocak.skj.jooq.tables.records;


import com.github.senocak.skj.jooq.tables.EmailActivationTokens;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailActivationTokensRecord extends UpdatableRecordImpl<EmailActivationTokensRecord> implements Record6<UUID, LocalDateTime, LocalDateTime, LocalDateTime, String, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.email_activation_tokens.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.email_activation_tokens.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.email_activation_tokens.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.email_activation_tokens.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.email_activation_tokens.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.email_activation_tokens.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.email_activation_tokens.expiration_date</code>.
     */
    public void setExpirationDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.email_activation_tokens.expiration_date</code>.
     */
    public LocalDateTime getExpirationDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.email_activation_tokens.token</code>.
     */
    public void setToken(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.email_activation_tokens.token</code>.
     */
    public String getToken() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.email_activation_tokens.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.email_activation_tokens.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, LocalDateTime, LocalDateTime, LocalDateTime, String, UUID> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, LocalDateTime, LocalDateTime, LocalDateTime, String, UUID> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return EmailActivationTokens.EMAIL_ACTIVATION_TOKENS.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return EmailActivationTokens.EMAIL_ACTIVATION_TOKENS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return EmailActivationTokens.EMAIL_ACTIVATION_TOKENS.UPDATED_AT;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return EmailActivationTokens.EMAIL_ACTIVATION_TOKENS.EXPIRATION_DATE;
    }

    @Override
    public Field<String> field5() {
        return EmailActivationTokens.EMAIL_ACTIVATION_TOKENS.TOKEN;
    }

    @Override
    public Field<UUID> field6() {
        return EmailActivationTokens.EMAIL_ACTIVATION_TOKENS.USER_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime component4() {
        return getExpirationDate();
    }

    @Override
    public String component5() {
        return getToken();
    }

    @Override
    public UUID component6() {
        return getUserId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime value4() {
        return getExpirationDate();
    }

    @Override
    public String value5() {
        return getToken();
    }

    @Override
    public UUID value6() {
        return getUserId();
    }

    @Override
    public EmailActivationTokensRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public EmailActivationTokensRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public EmailActivationTokensRecord value3(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public EmailActivationTokensRecord value4(LocalDateTime value) {
        setExpirationDate(value);
        return this;
    }

    @Override
    public EmailActivationTokensRecord value5(String value) {
        setToken(value);
        return this;
    }

    @Override
    public EmailActivationTokensRecord value6(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public EmailActivationTokensRecord values(UUID value1, LocalDateTime value2, LocalDateTime value3, LocalDateTime value4, String value5, UUID value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmailActivationTokensRecord
     */
    public EmailActivationTokensRecord() {
        super(EmailActivationTokens.EMAIL_ACTIVATION_TOKENS);
    }

    /**
     * Create a detached, initialised EmailActivationTokensRecord
     */
    public EmailActivationTokensRecord(UUID id, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime expirationDate, String token, UUID userId) {
        super(EmailActivationTokens.EMAIL_ACTIVATION_TOKENS);

        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setExpirationDate(expirationDate);
        setToken(token);
        setUserId(userId);
        resetChangedOnNotNull();
    }
}
