/*
 * This file is generated by jOOQ.
 */
package com.github.senocak.skj.jooq.tables;


import com.github.senocak.skj.jooq.Keys;
import com.github.senocak.skj.jooq.Public;
import com.github.senocak.skj.jooq.tables.records.EmailActivationTokensRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailActivationTokens extends TableImpl<EmailActivationTokensRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.email_activation_tokens</code>
     */
    public static final EmailActivationTokens EMAIL_ACTIVATION_TOKENS = new EmailActivationTokens();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmailActivationTokensRecord> getRecordType() {
        return EmailActivationTokensRecord.class;
    }

    /**
     * The column <code>public.email_activation_tokens.id</code>.
     */
    public final TableField<EmailActivationTokensRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.email_activation_tokens.created_at</code>.
     */
    public final TableField<EmailActivationTokensRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.email_activation_tokens.updated_at</code>.
     */
    public final TableField<EmailActivationTokensRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.email_activation_tokens.expiration_date</code>.
     */
    public final TableField<EmailActivationTokensRecord, LocalDateTime> EXPIRATION_DATE = createField(DSL.name("expiration_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.email_activation_tokens.token</code>.
     */
    public final TableField<EmailActivationTokensRecord, String> TOKEN = createField(DSL.name("token"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.email_activation_tokens.user_id</code>.
     */
    public final TableField<EmailActivationTokensRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    private EmailActivationTokens(Name alias, Table<EmailActivationTokensRecord> aliased) {
        this(alias, aliased, null);
    }

    private EmailActivationTokens(Name alias, Table<EmailActivationTokensRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.email_activation_tokens</code> table
     * reference
     */
    public EmailActivationTokens(String alias) {
        this(DSL.name(alias), EMAIL_ACTIVATION_TOKENS);
    }

    /**
     * Create an aliased <code>public.email_activation_tokens</code> table
     * reference
     */
    public EmailActivationTokens(Name alias) {
        this(alias, EMAIL_ACTIVATION_TOKENS);
    }

    /**
     * Create a <code>public.email_activation_tokens</code> table reference
     */
    public EmailActivationTokens() {
        this(DSL.name("email_activation_tokens"), null);
    }

    public <O extends Record> EmailActivationTokens(Table<O> child, ForeignKey<O, EmailActivationTokensRecord> key) {
        super(child, key, EMAIL_ACTIVATION_TOKENS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<EmailActivationTokensRecord> getPrimaryKey() {
        return Keys.EMAIL_ACTIVATION_TOKENS_PKEY;
    }

    @Override
    public List<UniqueKey<EmailActivationTokensRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UK_EMAIL_ACTIVATION_TOKENS_TOKEN);
    }

    @Override
    public List<ForeignKey<EmailActivationTokensRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EMAIL_ACTIVATION_TOKENS__FK_EMAIL_ACTIVATION_TOKENS_USER_USER_ID);
    }

    private transient Users _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.EMAIL_ACTIVATION_TOKENS__FK_EMAIL_ACTIVATION_TOKENS_USER_USER_ID);

        return _users;
    }

    @Override
    public EmailActivationTokens as(String alias) {
        return new EmailActivationTokens(DSL.name(alias), this);
    }

    @Override
    public EmailActivationTokens as(Name alias) {
        return new EmailActivationTokens(alias, this);
    }

    @Override
    public EmailActivationTokens as(Table<?> alias) {
        return new EmailActivationTokens(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailActivationTokens rename(String name) {
        return new EmailActivationTokens(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailActivationTokens rename(Name name) {
        return new EmailActivationTokens(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailActivationTokens rename(Table<?> name) {
        return new EmailActivationTokens(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, LocalDateTime, LocalDateTime, LocalDateTime, String, UUID> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super UUID, ? super LocalDateTime, ? super LocalDateTime, ? super LocalDateTime, ? super String, ? super UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super UUID, ? super LocalDateTime, ? super LocalDateTime, ? super LocalDateTime, ? super String, ? super UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
