/*
 * This file is generated by jOOQ.
 */
package com.github.senocak.skj.jooq;


import com.github.senocak.skj.jooq.tables.AuditRevisionEntity;
import com.github.senocak.skj.jooq.tables.EmailActivationTokens;
import com.github.senocak.skj.jooq.tables.EmailActivationTokensAud;
import com.github.senocak.skj.jooq.tables.FlywaySchemaHistory;
import com.github.senocak.skj.jooq.tables.Roles;
import com.github.senocak.skj.jooq.tables.UserAudit;
import com.github.senocak.skj.jooq.tables.UserRoles;
import com.github.senocak.skj.jooq.tables.UserRolesAud;
import com.github.senocak.skj.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.audit_revision_entity</code>.
     */
    public final AuditRevisionEntity AUDIT_REVISION_ENTITY = AuditRevisionEntity.AUDIT_REVISION_ENTITY;

    /**
     * The table <code>public.email_activation_tokens</code>.
     */
    public final EmailActivationTokens EMAIL_ACTIVATION_TOKENS = EmailActivationTokens.EMAIL_ACTIVATION_TOKENS;

    /**
     * The table <code>public.email_activation_tokens_aud</code>.
     */
    public final EmailActivationTokensAud EMAIL_ACTIVATION_TOKENS_AUD = EmailActivationTokensAud.EMAIL_ACTIVATION_TOKENS_AUD;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.user_audit</code>.
     */
    public final UserAudit USER_AUDIT = UserAudit.USER_AUDIT;

    /**
     * The table <code>public.user_roles</code>.
     */
    public final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>public.user_roles_aud</code>.
     */
    public final UserRolesAud USER_ROLES_AUD = UserRolesAud.USER_ROLES_AUD;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.AUDIT_REVISION_ENTITY_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuditRevisionEntity.AUDIT_REVISION_ENTITY,
            EmailActivationTokens.EMAIL_ACTIVATION_TOKENS,
            EmailActivationTokensAud.EMAIL_ACTIVATION_TOKENS_AUD,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Roles.ROLES,
            UserAudit.USER_AUDIT,
            UserRoles.USER_ROLES,
            UserRolesAud.USER_ROLES_AUD,
            Users.USERS
        );
    }
}
