/*
 * This file is generated by jOOQ.
 */
package com.github.senocak.skj.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.audit_revision_entity_seq</code>
     */
    public static final Sequence<Long> AUDIT_REVISION_ENTITY_SEQ = Internal.createSequence("audit_revision_entity_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, 50, null, null, false, null);
}
