/*
 * This file is generated by jOOQ.
 */
package com.github.senocak.skj.jooq;


import com.github.senocak.skj.jooq.tables.AuditRevisionEntity;
import com.github.senocak.skj.jooq.tables.EmailActivationTokens;
import com.github.senocak.skj.jooq.tables.EmailActivationTokensAud;
import com.github.senocak.skj.jooq.tables.FlywaySchemaHistory;
import com.github.senocak.skj.jooq.tables.Roles;
import com.github.senocak.skj.jooq.tables.UserAudit;
import com.github.senocak.skj.jooq.tables.UserRoles;
import com.github.senocak.skj.jooq.tables.UserRolesAud;
import com.github.senocak.skj.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.audit_revision_entity</code>.
     */
    public static final AuditRevisionEntity AUDIT_REVISION_ENTITY = AuditRevisionEntity.AUDIT_REVISION_ENTITY;

    /**
     * The table <code>public.email_activation_tokens</code>.
     */
    public static final EmailActivationTokens EMAIL_ACTIVATION_TOKENS = EmailActivationTokens.EMAIL_ACTIVATION_TOKENS;

    /**
     * The table <code>public.email_activation_tokens_aud</code>.
     */
    public static final EmailActivationTokensAud EMAIL_ACTIVATION_TOKENS_AUD = EmailActivationTokensAud.EMAIL_ACTIVATION_TOKENS_AUD;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.user_audit</code>.
     */
    public static final UserAudit USER_AUDIT = UserAudit.USER_AUDIT;

    /**
     * The table <code>public.user_roles</code>.
     */
    public static final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>public.user_roles_aud</code>.
     */
    public static final UserRolesAud USER_ROLES_AUD = UserRolesAud.USER_ROLES_AUD;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
